import type { SiteConfig, Category, Product, Testimonial } from './types';

export const siteConfig: SiteConfig = {
  businessName: 'Clover Garden Centre',
  tagline: 'Rooted in what we love',
  phone: '3305550147',
  phoneDisplay: '(330) 555-0147',
  email: 'hello@clovergardenhudson.com',
  address: '4892 Darrow Rd, Hudson, OH 44236',
  founded: 1987,
  hours: [
    { day: 'Monday – Saturday', hours: '8:00 AM – 6:00 PM' },
    { day: 'Sunday', hours: '10:00 AM – 4:00 PM' },
  ],
};

export const categories: Category[] = [
  {
    id: '1',
    slug: 'annuals',
    name: 'Annuals',
    description: 'Vibrant seasonal color all summer long',
    productCount: 48,
    imageSrc: '/images/category-annuals.jpg',
    imageAlt: 'Colorful annual flowers in bloom',
    accentColor: 'from-rose-900/30',
  },
  {
    id: '2',
    slug: 'perennials',
    name: 'Perennials',
    description: 'Plant once, enjoy for years to come',
    productCount: 62,
    imageSrc: '/images/category-perennials.jpg',
    imageAlt: 'Perennial garden in full bloom',
    accentColor: 'from-purple-900/30',
  },
  {
    id: '3',
    slug: 'trees-shrubs',
    name: 'Trees & Shrubs',
    description: 'Structure and shade for every landscape',
    productCount: 35,
    imageSrc: '/images/category-tress-shrubs.jpg',
    imageAlt: 'Trees and shrubs in a nursery',
    accentColor: 'from-green-900/40',
  },
  {
    id: '4',
    slug: 'houseplants',
    name: 'Houseplants',
    description: 'Bring the garden indoors',
    productCount: 54,
    imageSrc: '/images/category-houseplants.jpg',
    imageAlt: 'Lush indoor houseplants',
    accentColor: 'from-emerald-900/30',
  },
  {
    id: '5',
    slug: 'garden-supplies',
    name: 'Garden Supplies',
    description: 'Everything you need to grow well',
    productCount: 89,
    imageSrc: '/images/category-garden-supplies.jpg',
    imageAlt: 'Garden tools and supplies',
    accentColor: 'from-amber-900/30',
  },
  {
    id: '6',
    slug: 'pots-planters',
    name: 'Pots & Planters',
    description: 'Beautiful homes for beautiful plants',
    productCount: 41,
    imageSrc: '/images/category-pots-planters.jpg',
    imageAlt: 'Terracotta and ceramic planters',
    accentColor: 'from-orange-900/30',
  },
];

export const products: Product[] = [
  {
    id: '1',
    slug: 'lavender-hidcote',
    name: "Lavender 'Hidcote'",
    category: 'Perennials',
    categorySlug: 'perennials',
    shortDescription: 'Deep violet spikes, intensely fragrant, drought-tolerant once established.',
    price: 14.99,
    unit: '1 qt. pot',
    rating: 5,
    reviewCount: 84,
    badge: 'bestseller',
    imageSrc: null,
    imageAlt: 'Lavender Hidcote in bloom',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    slug: 'hydrangea-endless-summer',
    name: "Hydrangea 'Endless Summer'",
    category: 'Shrubs',
    categorySlug: 'trees-shrubs',
    shortDescription: 'Reblooming mophead — blue in acidic soil, pink in alkaline. Re-blooms reliably.',
    price: 34.99,
    originalPrice: 44.99,
    unit: '2 gal. pot',
    rating: 5,
    reviewCount: 112,
    badge: 'sale',
    imageSrc: null,
    imageAlt: 'Blue hydrangea in full bloom',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    slug: 'monstera-deliciosa',
    name: 'Monstera deliciosa',
    category: 'Houseplants',
    categorySlug: 'houseplants',
    shortDescription: 'The iconic split-leaf tropical. Easy care, fast growing, statement-making.',
    price: 32.99,
    unit: '6" pot',
    rating: 5,
    reviewCount: 67,
    badge: 'new',
    imageSrc: null,
    imageAlt: 'Large Monstera deliciosa plant',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    slug: 'marigold-six-pack',
    name: 'Marigold Mix 6-Pack',
    category: 'Annuals',
    categorySlug: 'annuals',
    shortDescription: 'Classic gold and orange blooms. Deer-resistant and great for borders.',
    price: 7.99,
    unit: '6-pack',
    rating: 4,
    reviewCount: 203,
    badge: 'seasonal',
    imageSrc: null,
    imageAlt: 'Orange and yellow marigolds',
    inStock: true,
    featured: false,
  },
  {
    id: '5',
    slug: 'japanese-maple-bloodgood',
    name: "Japanese Maple 'Bloodgood'",
    category: 'Trees',
    categorySlug: 'trees-shrubs',
    shortDescription: 'Deep burgundy foliage turns crimson in fall. Elegant upright form to 15 ft.',
    price: 124.99,
    unit: '5 gal. pot',
    rating: 5,
    reviewCount: 38,
    imageSrc: null,
    imageAlt: 'Japanese Maple with deep red foliage',
    inStock: true,
    stockNote: 'Only 6 left',
    featured: true,
  },
  {
    id: '6',
    slug: 'knockout-rose',
    name: "Rose 'Knock Out'",
    category: 'Shrubs',
    categorySlug: 'trees-shrubs',
    shortDescription: 'Self-cleaning, disease-resistant, and non-stop blooming from spring to frost.',
    price: 29.99,
    unit: '2 gal. pot',
    rating: 5,
    reviewCount: 156,
    badge: 'bestseller',
    imageSrc: null,
    imageAlt: 'Bright red Knock Out rose in bloom',
    inStock: true,
    featured: true,
  },
  {
    id: '7',
    slug: 'daylily-stella-doro',
    name: "Daylily 'Stella d'Oro'",
    category: 'Perennials',
    categorySlug: 'perennials',
    shortDescription: 'Gold-yellow flowers rebloom all summer. Tough, adaptable, and low-maintenance.',
    price: 11.99,
    unit: '1 qt. pot',
    rating: 4,
    reviewCount: 91,
    imageSrc: null,
    imageAlt: 'Yellow Stella dOro daylily',
    inStock: true,
    featured: false,
  },
  {
    id: '8',
    slug: 'peace-lily',
    name: 'Peace Lily',
    category: 'Houseplants',
    categorySlug: 'houseplants',
    shortDescription: "One of the best air-purifying houseplants. Tolerates low light beautifully.",
    price: 19.99,
    unit: '6" pot',
    rating: 4,
    reviewCount: 78,
    imageSrc: null,
    imageAlt: 'Peace lily with white blooms',
    inStock: true,
    featured: false,
  },
  {
    id: '9',
    slug: 'terracotta-planter-12',
    name: 'Hand-Thrown Terracotta Pot, 12"',
    category: 'Pots & Planters',
    categorySlug: 'pots-planters',
    shortDescription: 'Italian terracotta, wheel-thrown by hand. Drainage hole included.',
    price: 24.99,
    unit: 'each',
    rating: 5,
    reviewCount: 44,
    badge: 'new',
    imageSrc: null,
    imageAlt: '12-inch terracotta pot',
    inStock: true,
    featured: false,
  },
  {
    id: '10',
    slug: 'premium-potting-mix',
    name: 'Premium Potting Mix',
    category: 'Garden Supplies',
    categorySlug: 'garden-supplies',
    shortDescription: 'Locally blended with compost, perlite, and slow-release fertilizer.',
    price: 18.99,
    originalPrice: 22.99,
    unit: '40 L bag',
    rating: 5,
    reviewCount: 229,
    badge: 'sale',
    imageSrc: null,
    imageAlt: 'Bag of premium potting mix',
    inStock: true,
    featured: false,
  },
  {
    id: '11',
    slug: 'basil-herb-collection',
    name: 'Herb Garden 3-Pack',
    category: 'Annuals',
    categorySlug: 'annuals',
    shortDescription: 'Basil, parsley, and chives — ready to plant or pot. Organic starts.',
    price: 10.99,
    unit: '3-pack',
    rating: 4,
    reviewCount: 63,
    badge: 'seasonal',
    imageSrc: null,
    imageAlt: 'Fresh herb garden starter pack',
    inStock: true,
    featured: false,
  },
  {
    id: '12',
    slug: 'heirloom-vegetable-seed-kit',
    name: 'Heirloom Vegetable Seed Kit',
    category: 'Garden Supplies',
    categorySlug: 'garden-supplies',
    shortDescription: '12 varieties of open-pollinated heirloom seeds, curated for Ohio gardens.',
    price: 16.99,
    unit: 'kit',
    rating: 5,
    reviewCount: 51,
    badge: 'new',
    imageSrc: null,
    imageAlt: 'Collection of heirloom vegetable seeds',
    inStock: true,
    featured: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Margaret H.',
    location: 'Hudson, OH',
    rating: 5,
    quote:
      "I've been coming to Clover since the early nineties. The staff actually knows plants — not just how to ring them up, but which varieties will thrive in our clay soil, which ones the deer will leave alone. That kind of knowledge is irreplaceable. My garden is proof.",
    context: 'Loyal customer since 1993',
  },
  {
    id: '2',
    name: 'Tom & Lisa P.',
    location: 'Stow, OH',
    rating: 5,
    quote:
      "We redid our entire backyard this spring using Clover's design consultation service. They walked through our space, understood our vision, and recommended plants we never would have found at a big box store. Couldn't be happier.",
    context: 'Full landscape overhaul',
  },
  {
    id: '3',
    name: 'Diana K.',
    location: 'Chagrin Falls, OH',
    rating: 5,
    quote:
      "The houseplant selection is unlike anywhere else in the area. I drove 40 minutes specifically for the Monstera and left with six plants I didn't know I needed. Highly recommend the greenhouse walk-through on a weekend morning.",
    context: 'Houseplant enthusiast',
  },
];
