<?php
/**
 * Project ACF Field Group
 *
 * @package portfolio-headless-cms
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

acf_add_local_field_group( array(
    'key'                   => 'group_project_details',
    'title'                 => esc_html__( 'Project Details', 'portfolio-headless-cms' ),
    'fields'                => array(
        // URLs & Links Tab
        array(
            'key'               => 'field_project_urls_tab',
            'label'             => esc_html__( 'URLs & Links', 'portfolio-headless-cms' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'               => 'field_live_url',
            'label'             => esc_html__( 'Live Site URL', 'portfolio-headless-cms' ),
            'name'              => 'live_url',
            'type'              => 'url',
            'instructions'      => esc_html__( 'The live URL to your deployed project', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'https://example.com',
        ),
        array(
            'key'               => 'field_github_url',
            'label'             => esc_html__( 'GitHub Repository URL', 'portfolio-headless-cms' ),
            'name'              => 'github_url',
            'type'              => 'url',
            'instructions'      => esc_html__( 'Link to the GitHub repository', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'https://github.com/username/repo',
        ),
        array(
            'key'               => 'field_iframe_embed_url',
            'label'             => esc_html__( 'Interactive Preview URL', 'portfolio-headless-cms' ),
            'name'              => 'iframe_embed_url',
            'type'              => 'url',
            'instructions'      => esc_html__( 'URL for the interactive preview iframe (e.g., Figma prototype, CodePen embed)', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'https://example.com/embed',
        ),

        // Media Tab
        array(
            'key'               => 'field_project_media_tab',
            'label'             => esc_html__( 'Media', 'portfolio-headless-cms' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'               => 'field_project_gif',
            'label'             => esc_html__( 'Project Walkthrough GIF/Video', 'portfolio-headless-cms' ),
            'name'              => 'project_gif',
            'type'              => 'file',
            'instructions'      => esc_html__( 'Upload a GIF or video file showing the project in action', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'return_format'     => 'url',
            'library'           => 'all',
            'mime_types'        => 'gif,mp4,webm',
        ),
        array(
            'key'               => 'field_project_color',
            'label'             => esc_html__( 'Project Brand Color', 'portfolio-headless-cms' ),
            'name'              => 'project_color',
            'type'              => 'color_picker',
            'instructions'      => esc_html__( 'Choose a brand color for the project', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => '#000000',
            'enable_opacity'    => 0,
            'return_format'     => 'string',
        ),
        array(
            'key'               => 'field_project_gallery',
            'label'             => esc_html__( 'Project Screenshots', 'portfolio-headless-cms' ),
            'name'              => 'project_gallery',
            'type'              => 'gallery',
            'instructions'      => esc_html__( 'Add screenshots or images showing your project', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'return_format'     => 'array',
            'library'           => 'all',
            'min'               => '',
            'max'               => '',
            'insert'            => 'append',
            'allow_link'        => 0,
        ),

        // Details Tab
        array(
            'key'               => 'field_project_details_tab',
            'label'             => esc_html__( 'Details', 'portfolio-headless-cms' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'               => 'field_client_name',
            'label'             => esc_html__( 'Client Name', 'portfolio-headless-cms' ),
            'name'              => 'client_name',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
        ),
        array(
            'key'               => 'field_project_date',
            'label'             => esc_html__( 'Completion Date', 'portfolio-headless-cms' ),
            'name'              => 'project_date',
            'type'              => 'date_picker',
            'instructions'      => esc_html__( 'When was the project completed?', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'display_format'    => 'm/d/Y',
            'return_format'     => 'Y-m-d',
            'first_day'         => 1,
        ),
        array(
            'key'               => 'field_project_duration',
            'label'             => esc_html__( 'Project Duration', 'portfolio-headless-cms' ),
            'name'              => 'project_duration',
            'type'              => 'text',
            'instructions'      => esc_html__( 'e.g., "3 months", "6 weeks"', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '3 months',
        ),
        array(
            'key'               => 'field_is_featured',
            'label'             => esc_html__( 'Featured Project', 'portfolio-headless-cms' ),
            'name'              => 'is_featured',
            'type'              => 'true_false',
            'instructions'      => esc_html__( 'Show this project in the featured projects section', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'message'           => '',
            'default_value'     => 0,
            'ui'                => 1,
            'ui_on_text'        => 'Yes',
            'ui_off_text'       => 'No',
        ),
        array(
            'key'               => 'field_project_order',
            'label'             => esc_html__( 'Display Order', 'portfolio-headless-cms' ),
            'name'              => 'project_order',
            'type'              => 'number',
            'instructions'      => esc_html__( 'Lower numbers appear first', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => 0,
            'min'               => 0,
            'max'               => '',
            'step'              => 1,
        ),

        // Testimonial Tab
        array(
            'key'               => 'field_project_testimonial_tab',
            'label'             => esc_html__( 'Testimonial', 'portfolio-headless-cms' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'placement'         => 'top',
            'endpoint'          => 0,
        ),
        array(
            'key'               => 'field_project_testimonial',
            'label'             => esc_html__( 'Client Testimonial', 'portfolio-headless-cms' ),
            'name'              => 'project_testimonial',
            'type'              => 'textarea',
            'instructions'      => esc_html__( 'What did your client say about the project?', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'maxlength'         => '',
            'rows'              => 4,
            'new_lines'         => 'wpautop',
        ),
        array(
            'key'               => 'field_testimonial_author',
            'label'             => esc_html__( 'Testimonial Author', 'portfolio-headless-cms' ),
            'name'              => 'testimonial_author',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'John Doe',
        ),
        array(
            'key'               => 'field_testimonial_role',
            'label'             => esc_html__( 'Author Role/Title', 'portfolio-headless-cms' ),
            'name'              => 'testimonial_role',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'CEO, Company Name',
        ),

        // SEO Tab
        array(
            'key'               => 'field_project_seo_tab',
            'label'             => esc_html__( 'SEO', 'portfolio-headless-cms' ),
            'name'              => '',
            'type'              => 'tab',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '',
                'class' => '',
                'id'    => '',
            ),
            'placement'         => 'top',
            'endpoint'          => 1,
        ),
        array(
            'key'               => 'field_seo_title',
            'label'             => esc_html__( 'SEO Title Override', 'portfolio-headless-cms' ),
            'name'              => 'seo_title',
            'type'              => 'text',
            'instructions'      => esc_html__( 'Leave blank to use the post title', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'maxlength'         => 60,
        ),
        array(
            'key'               => 'field_seo_description',
            'label'             => esc_html__( 'Meta Description', 'portfolio-headless-cms' ),
            'name'              => 'seo_description',
            'type'              => 'textarea',
            'instructions'      => esc_html__( 'Max 160 characters', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'maxlength'         => 160,
            'rows'              => 2,
            'new_lines'         => '',
        ),
        array(
            'key'               => 'field_seo_keywords',
            'label'             => esc_html__( 'Focus Keywords', 'portfolio-headless-cms' ),
            'name'              => 'seo_keywords',
            'type'              => 'text',
            'instructions'      => esc_html__( 'Comma-separated keywords', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'keyword1, keyword2, keyword3',
        ),
    ),
    'location'              => array(
        array(
            array(
                'param'    => 'post_type',
                'operator' => '==',
                'value'    => 'project',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => esc_html__( 'Fields for portfolio projects', 'portfolio-headless-cms' ),
    'show_in_graphql'       => true,
    'graphql_field_name'    => 'projectDetails',
) );
