<?php
/**
 * Global Options and Site Settings ACF Fields
 *
 * @package portfolio-headless-cms
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

/**
 * Register Site Settings Options Pages
 */
if ( function_exists( 'acf_add_options_page' ) ) {
    // Main options page
    $main_page = acf_add_options_page( array(
        'page_title' => esc_html__( 'Site Settings', 'portfolio-headless-cms' ),
        'menu_title' => esc_html__( 'Site Settings', 'portfolio-headless-cms' ),
        'menu_slug'  => 'site-settings',
        'capability' => 'manage_options',
        'redirect'   => false,
        'position'   => '4.5',
    ) );

    // Header sub-page
    acf_add_options_sub_page( array(
        'page_title' => esc_html__( 'Header & Navigation', 'portfolio-headless-cms' ),
        'menu_title' => esc_html__( 'Header & Navigation', 'portfolio-headless-cms' ),
        'menu_slug'  => 'site-settings-header',
        'parent_slug' => 'site-settings',
        'capability' => 'manage_options',
    ) );

    // Footer sub-page
    acf_add_options_sub_page( array(
        'page_title' => esc_html__( 'Footer Settings', 'portfolio-headless-cms' ),
        'menu_title' => esc_html__( 'Footer Settings', 'portfolio-headless-cms' ),
        'menu_slug'  => 'site-settings-footer',
        'parent_slug' => 'site-settings',
        'capability' => 'manage_options',
    ) );

    // Homepage sub-page
    acf_add_options_sub_page( array(
        'page_title' => esc_html__( 'Homepage Settings', 'portfolio-headless-cms' ),
        'menu_title' => esc_html__( 'Homepage Settings', 'portfolio-headless-cms' ),
        'menu_slug'  => 'site-settings-homepage',
        'parent_slug' => 'site-settings',
        'capability' => 'manage_options',
    ) );

    // SEO Defaults sub-page
    acf_add_options_sub_page( array(
        'page_title' => esc_html__( 'SEO Defaults', 'portfolio-headless-cms' ),
        'menu_title' => esc_html__( 'SEO Defaults', 'portfolio-headless-cms' ),
        'menu_slug'  => 'site-settings-seo',
        'parent_slug' => 'site-settings',
        'capability' => 'manage_options',
    ) );
}

/**
 * Header Settings Field Group
 */
acf_add_local_field_group( array(
    'key'                   => 'group_header_settings',
    'title'                 => esc_html__( 'Header Settings', 'portfolio-headless-cms' ),
    'fields'                => array(
        array(
            'key'               => 'field_header_cta_text',
            'label'             => esc_html__( 'Header CTA Text', 'portfolio-headless-cms' ),
            'name'              => 'header_cta_text',
            'type'              => 'text',
            'instructions'      => esc_html__( 'Button text in the header navigation', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( "Let's Talk", 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_header_cta_url',
            'label'             => esc_html__( 'Header CTA URL', 'portfolio-headless-cms' ),
            'name'              => 'header_cta_url',
            'type'              => 'url',
            'instructions'      => esc_html__( 'Where should the header CTA button link?', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '#contact',
        ),
        array(
            'key'               => 'field_announcement_bar_text',
            'label'             => esc_html__( 'Announcement Bar Text', 'portfolio-headless-cms' ),
            'name'              => 'announcement_bar_text',
            'type'              => 'text',
            'instructions'      => esc_html__( 'Text to display in the announcement bar at the top of the site', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'Check out my latest blog post!',
        ),
        array(
            'key'               => 'field_announcement_bar_active',
            'label'             => esc_html__( 'Show Announcement', 'portfolio-headless-cms' ),
            'name'              => 'announcement_bar_active',
            'type'              => 'true_false',
            'instructions'      => esc_html__( 'Display the announcement bar', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'message'           => '',
            'default_value'     => 0,
            'ui'                => 1,
            'ui_on_text'        => 'Yes',
            'ui_off_text'       => 'No',
        ),
    ),
    'location'              => array(
        array(
            array(
                'param'    => 'options_page',
                'operator' => '==',
                'value'    => 'site-settings-header',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => esc_html__( 'Header and navigation settings', 'portfolio-headless-cms' ),
    'show_in_graphql'       => true,
    'graphql_field_name'    => 'headerSettings',
) );

/**
 * Footer Settings Field Group
 */
acf_add_local_field_group( array(
    'key'                   => 'group_footer_settings',
    'title'                 => esc_html__( 'Footer Settings', 'portfolio-headless-cms' ),
    'fields'                => array(
        array(
            'key'               => 'field_footer_tagline',
            'label'             => esc_html__( 'Footer Tagline', 'portfolio-headless-cms' ),
            'name'              => 'footer_tagline',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'Cleveland WordPress & Full Stack Developer',
        ),
        array(
            'key'               => 'field_social_links',
            'label'             => esc_html__( 'Social Links', 'portfolio-headless-cms' ),
            'name'              => 'social_links',
            'type'              => 'repeater',
            'instructions'      => esc_html__( 'Add your social media links', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'collapsed'         => '',
            'min'               => 0,
            'max'               => '',
            'layout'            => 'table',
            'button_label'      => esc_html__( 'Add Social Link', 'portfolio-headless-cms' ),
            'sub_fields'        => array(
                array(
                    'key'               => 'field_social_platform',
                    'label'             => esc_html__( 'Platform', 'portfolio-headless-cms' ),
                    'name'              => 'platform',
                    'type'              => 'select',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'choices'           => array(
                        'github'   => esc_html__( 'GitHub', 'portfolio-headless-cms' ),
                        'linkedin' => esc_html__( 'LinkedIn', 'portfolio-headless-cms' ),
                        'twitter'  => esc_html__( 'Twitter', 'portfolio-headless-cms' ),
                        'dribbble' => esc_html__( 'Dribbble', 'portfolio-headless-cms' ),
                        'codepen'  => esc_html__( 'CodePen', 'portfolio-headless-cms' ),
                        'youtube'  => esc_html__( 'YouTube', 'portfolio-headless-cms' ),
                    ),
                    'default_value'     => '',
                    'allow_null'        => 0,
                    'multiple'          => 0,
                    'ui'                => 0,
                    'ajax'              => 0,
                    'return_format'     => 'value',
                    'placeholder'       => '',
                ),
                array(
                    'key'               => 'field_social_url',
                    'label'             => esc_html__( 'URL', 'portfolio-headless-cms' ),
                    'name'              => 'url',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => 'https://example.com',
                ),
            ),
        ),
        array(
            'key'               => 'field_footer_cta_heading',
            'label'             => esc_html__( 'CTA Heading', 'portfolio-headless-cms' ),
            'name'              => 'footer_cta_heading',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Ready to level up your web presence?', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_footer_cta_text',
            'label'             => esc_html__( 'CTA Button Text', 'portfolio-headless-cms' ),
            'name'              => 'footer_cta_text',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Get in Touch', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_footer_cta_url',
            'label'             => esc_html__( 'CTA URL', 'portfolio-headless-cms' ),
            'name'              => 'footer_cta_url',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '#contact',
        ),
    ),
    'location'              => array(
        array(
            array(
                'param'    => 'options_page',
                'operator' => '==',
                'value'    => 'site-settings-footer',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => esc_html__( 'Footer content and social links', 'portfolio-headless-cms' ),
    'show_in_graphql'       => true,
    'graphql_field_name'    => 'footerSettings',
) );

/**
 * Homepage Settings Field Group
 */
acf_add_local_field_group( array(
    'key'                   => 'group_homepage_settings',
    'title'                 => esc_html__( 'Homepage Settings', 'portfolio-headless-cms' ),
    'fields'                => array(
        array(
            'key'               => 'field_hero_heading',
            'label'             => esc_html__( 'Hero Heading', 'portfolio-headless-cms' ),
            'name'              => 'hero_heading',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Cleveland WordPress & Full Stack Developer', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_hero_subheading',
            'label'             => esc_html__( 'Hero Subheading', 'portfolio-headless-cms' ),
            'name'              => 'hero_subheading',
            'type'              => 'textarea',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'rows'              => 3,
        ),
        array(
            'key'               => 'field_hero_cta_primary_text',
            'label'             => esc_html__( 'Primary CTA Text', 'portfolio-headless-cms' ),
            'name'              => 'hero_cta_primary_text',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'View My Work', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_hero_cta_primary_url',
            'label'             => esc_html__( 'Primary CTA URL', 'portfolio-headless-cms' ),
            'name'              => 'hero_cta_primary_url',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '#projects',
        ),
        array(
            'key'               => 'field_hero_cta_secondary_text',
            'label'             => esc_html__( 'Secondary CTA Text', 'portfolio-headless-cms' ),
            'name'              => 'hero_cta_secondary_text',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Get in Touch', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_hero_cta_secondary_url',
            'label'             => esc_html__( 'Secondary CTA URL', 'portfolio-headless-cms' ),
            'name'              => 'hero_cta_secondary_url',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '#contact',
        ),
        array(
            'key'               => 'field_stats',
            'label'             => esc_html__( 'Statistics', 'portfolio-headless-cms' ),
            'name'              => 'stats',
            'type'              => 'repeater',
            'instructions'      => esc_html__( 'Add statistics to display on the homepage', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'collapsed'         => '',
            'min'               => 0,
            'max'               => '',
            'layout'            => 'table',
            'button_label'      => esc_html__( 'Add Statistic', 'portfolio-headless-cms' ),
            'sub_fields'        => array(
                array(
                    'key'               => 'field_stat_number',
                    'label'             => esc_html__( 'Number', 'portfolio-headless-cms' ),
                    'name'              => 'stat_number',
                    'type'              => 'text',
                    'instructions'      => esc_html__( 'e.g., "50+"', 'portfolio-headless-cms' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => '50+',
                ),
                array(
                    'key'               => 'field_stat_label',
                    'label'             => esc_html__( 'Label', 'portfolio-headless-cms' ),
                    'name'              => 'stat_label',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '50',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => 'Projects Completed',
                ),
            ),
        ),
        array(
            'key'               => 'field_maintenance_section_heading',
            'label'             => esc_html__( 'Maintenance Section Heading', 'portfolio-headless-cms' ),
            'name'              => 'maintenance_section_heading',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'WordPress Maintenance & Support', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_maintenance_section_text',
            'label'             => esc_html__( 'Maintenance Section Description', 'portfolio-headless-cms' ),
            'name'              => 'maintenance_section_text',
            'type'              => 'textarea',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
            'rows'              => 4,
        ),
        array(
            'key'               => 'field_maintenance_features',
            'label'             => esc_html__( 'Maintenance Features', 'portfolio-headless-cms' ),
            'name'              => 'maintenance_features',
            'type'              => 'repeater',
            'instructions'      => esc_html__( 'Add features for the maintenance section', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'collapsed'         => '',
            'min'               => 0,
            'max'               => '',
            'layout'            => 'block',
            'button_label'      => esc_html__( 'Add Feature', 'portfolio-headless-cms' ),
            'sub_fields'        => array(
                array(
                    'key'               => 'field_maintenance_feature_icon',
                    'label'             => esc_html__( 'Icon', 'portfolio-headless-cms' ),
                    'name'              => 'feature_icon',
                    'type'              => 'text',
                    'instructions'      => esc_html__( 'Lucide icon name', 'portfolio-headless-cms' ),
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => 'shield',
                ),
                array(
                    'key'               => 'field_maintenance_feature_title',
                    'label'             => esc_html__( 'Title', 'portfolio-headless-cms' ),
                    'name'              => 'feature_title',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => 'Security Updates',
                ),
                array(
                    'key'               => 'field_maintenance_feature_desc',
                    'label'             => esc_html__( 'Description', 'portfolio-headless-cms' ),
                    'name'              => 'feature_description',
                    'type'              => 'textarea',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => '',
                    'rows'              => 2,
                ),
            ),
        ),
    ),
    'location'              => array(
        array(
            array(
                'param'    => 'options_page',
                'operator' => '==',
                'value'    => 'site-settings-homepage',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => esc_html__( 'Homepage hero and sections settings', 'portfolio-headless-cms' ),
    'show_in_graphql'       => true,
    'graphql_field_name'    => 'homepageSettings',
) );

/**
 * SEO Defaults Field Group
 */
acf_add_local_field_group( array(
    'key'                   => 'group_seo_defaults',
    'title'                 => esc_html__( 'SEO Defaults', 'portfolio-headless-cms' ),
    'fields'                => array(
        array(
            'key'               => 'field_default_og_image',
            'label'             => esc_html__( 'Default OG Image', 'portfolio-headless-cms' ),
            'name'              => 'default_og_image',
            'type'              => 'image',
            'instructions'      => esc_html__( 'Used when no featured image is available', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'return_format'     => 'array',
            'preview_size'      => 'medium',
            'library'           => 'all',
            'min_width'         => 1200,
            'min_height'        => 630,
            'min_size'          => '',
            'max_width'         => '',
            'max_height'        => '',
            'max_size'          => '',
            'mime_types'        => 'jpg,jpeg,png,gif,webp',
        ),
        array(
            'key'               => 'field_google_site_verification',
            'label'             => esc_html__( 'Google Site Verification', 'portfolio-headless-cms' ),
            'name'              => 'google_site_verification',
            'type'              => 'text',
            'instructions'      => esc_html__( 'Verification code from Google Search Console', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_schema_org_type',
            'label'             => esc_html__( 'Schema.org Type', 'portfolio-headless-cms' ),
            'name'              => 'schema_org_type',
            'type'              => 'select',
            'instructions'      => esc_html__( 'Structured data type for your site', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'choices'           => array(
                'Person'       => esc_html__( 'Person', 'portfolio-headless-cms' ),
                'Organization' => esc_html__( 'Organization', 'portfolio-headless-cms' ),
            ),
            'default_value'     => 'Person',
            'allow_null'        => 0,
            'multiple'          => 0,
            'ui'                => 0,
            'ajax'              => 0,
            'return_format'     => 'value',
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_schema_same_as',
            'label'             => esc_html__( 'Social Profile URLs', 'portfolio-headless-cms' ),
            'name'              => 'schema_same_as',
            'type'              => 'repeater',
            'instructions'      => esc_html__( 'Social profiles for Schema.org markup', 'portfolio-headless-cms' ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'collapsed'         => '',
            'min'               => 0,
            'max'               => '',
            'layout'            => 'table',
            'button_label'      => esc_html__( 'Add Profile', 'portfolio-headless-cms' ),
            'sub_fields'        => array(
                array(
                    'key'               => 'field_profile_url',
                    'label'             => esc_html__( 'Profile URL', 'portfolio-headless-cms' ),
                    'name'              => 'profile_url',
                    'type'              => 'url',
                    'instructions'      => '',
                    'required'          => 1,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '100',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placeholder'       => 'https://linkedin.com/in/username',
                ),
            ),
        ),
        array(
            'key'               => 'field_local_business_name',
            'label'             => esc_html__( 'Business Name', 'portfolio-headless-cms' ),
            'name'              => 'local_business_name',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '100',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Ray Turk Web Development', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_local_business_city',
            'label'             => esc_html__( 'City', 'portfolio-headless-cms' ),
            'name'              => 'local_business_city',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'Cleveland', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_local_business_state',
            'label'             => esc_html__( 'State', 'portfolio-headless-cms' ),
            'name'              => 'local_business_state',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => esc_html__( 'OH', 'portfolio-headless-cms' ),
            'placeholder'       => '',
        ),
        array(
            'key'               => 'field_local_business_phone',
            'label'             => esc_html__( 'Phone', 'portfolio-headless-cms' ),
            'name'              => 'local_business_phone',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => '+1 (216) 555-0000',
        ),
        array(
            'key'               => 'field_local_business_email',
            'label'             => esc_html__( 'Email', 'portfolio-headless-cms' ),
            'name'              => 'local_business_email',
            'type'              => 'email',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '50',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'hello@example.com',
        ),
    ),
    'location'              => array(
        array(
            array(
                'param'    => 'options_page',
                'operator' => '==',
                'value'    => 'site-settings-seo',
            ),
        ),
    ),
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen'        => '',
    'active'                => true,
    'description'           => esc_html__( 'Default SEO settings and structured data', 'portfolio-headless-cms' ),
    'show_in_graphql'       => true,
    'graphql_field_name'    => 'seoDefaults',
) );
